name: valutex_vibe
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl: "^0.15.6"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/data/countries.json
    - assets/data/rates.json
    - assets/images/flags/country_ad_64.png
    - assets/images/flags/country_ae_64.png
    - assets/images/flags/country_af_64.png
    - assets/images/flags/country_ag_64.png
    - assets/images/flags/country_ai_64.png
    - assets/images/flags/country_al_64.png
    - assets/images/flags/country_am_64.png
    - assets/images/flags/country_ao_64.png
    - assets/images/flags/country_aq_64.png
    - assets/images/flags/country_ar_64.png
    - assets/images/flags/country_as_64.png
    - assets/images/flags/country_at_64.png
    - assets/images/flags/country_au_64.png
    - assets/images/flags/country_aw_64.png
    - assets/images/flags/country_ax_64.png
    - assets/images/flags/country_az_64.png
    - assets/images/flags/country_ba_64.png
    - assets/images/flags/country_bb_64.png
    - assets/images/flags/country_bd_64.png
    - assets/images/flags/country_be_64.png
    - assets/images/flags/country_bf_64.png
    - assets/images/flags/country_bg_64.png
    - assets/images/flags/country_bh_64.png
    - assets/images/flags/country_bi_64.png
    - assets/images/flags/country_bj_64.png
    - assets/images/flags/country_bl_64.png
    - assets/images/flags/country_bm_64.png
    - assets/images/flags/country_bn_64.png
    - assets/images/flags/country_bo_64.png
    #- assets/images/flags/country_bq_64.png
    - assets/images/flags/country_br_64.png
    - assets/images/flags/country_bs_64.png
    - assets/images/flags/country_bt_64.png
    #- assets/images/flags/country_bv_64.png
    - assets/images/flags/country_bw_64.png
    - assets/images/flags/country_by_64.png
    - assets/images/flags/country_bz_64.png
    - assets/images/flags/country_ca_64.png
    - assets/images/flags/country_cc_64.png
    - assets/images/flags/country_cd_64.png
    - assets/images/flags/country_cf_64.png
    - assets/images/flags/country_cg_64.png
    - assets/images/flags/country_ch_64.png
    - assets/images/flags/country_ci_64.png
    - assets/images/flags/country_ck_64.png
    - assets/images/flags/country_cl_64.png
    - assets/images/flags/country_cm_64.png
    - assets/images/flags/country_cn_64.png
    - assets/images/flags/country_co_64.png
    - assets/images/flags/country_cr_64.png
    - assets/images/flags/country_cu_64.png
    - assets/images/flags/country_cv_64.png
    - assets/images/flags/country_cw_64.png
    - assets/images/flags/country_cx_64.png
    - assets/images/flags/country_cy_64.png
    - assets/images/flags/country_cz_64.png
    - assets/images/flags/country_de_64.png
    - assets/images/flags/country_dj_64.png
    - assets/images/flags/country_dk_64.png
    - assets/images/flags/country_dm_64.png
    - assets/images/flags/country_do_64.png
    - assets/images/flags/country_dz_64.png
    - assets/images/flags/country_ec_64.png
    - assets/images/flags/country_ee_64.png
    - assets/images/flags/country_eg_64.png
    - assets/images/flags/country_eh_64.png
    - assets/images/flags/country_er_64.png
    - assets/images/flags/country_es_64.png
    - assets/images/flags/country_et_64.png
    - assets/images/flags/country_eu_64.png
    - assets/images/flags/country_fi_64.png
    - assets/images/flags/country_fj_64.png
    - assets/images/flags/country_fk_64.png
    - assets/images/flags/country_fo_64.png
    - assets/images/flags/country_fr_64.png
    - assets/images/flags/country_ga_64.png
    - assets/images/flags/country_gb_64.png
    - assets/images/flags/country_gd_64.png
    - assets/images/flags/country_ge_64.png
    #- assets/images/flags/country_gf_64.png
    - assets/images/flags/country_gg_64.png
    - assets/images/flags/country_gh_64.png
    - assets/images/flags/country_gi_64.png
    - assets/images/flags/country_gl_64.png
    - assets/images/flags/country_gm_64.png
    - assets/images/flags/country_gn_64.png
    #- assets/images/flags/country_gp_64.png
    - assets/images/flags/country_gq_64.png
    - assets/images/flags/country_gr_64.png
    - assets/images/flags/country_gs_64.png
    - assets/images/flags/country_gt_64.png
    - assets/images/flags/country_gu_64.png
    - assets/images/flags/country_gw_64.png
    - assets/images/flags/country_gy_64.png
    - assets/images/flags/country_hk_64.png
    #- assets/images/flags/country_hm_64.png
    - assets/images/flags/country_hn_64.png
    - assets/images/flags/country_hr_64.png
    - assets/images/flags/country_ht_64.png
    - assets/images/flags/country_hu_64.png
    - assets/images/flags/country_id_64.png
    - assets/images/flags/country_ie_64.png
    - assets/images/flags/country_il_64.png
    - assets/images/flags/country_im_64.png
    - assets/images/flags/country_in_64.png
    #- assets/images/flags/country_io_64.png
    - assets/images/flags/country_iq_64.png
    - assets/images/flags/country_ir_64.png
    - assets/images/flags/country_is_64.png
    - assets/images/flags/country_it_64.png
    - assets/images/flags/country_je_64.png
    - assets/images/flags/country_jm_64.png
    - assets/images/flags/country_jo_64.png
    - assets/images/flags/country_jp_64.png
    - assets/images/flags/country_ke_64.png
    - assets/images/flags/country_kg_64.png
    - assets/images/flags/country_kh_64.png
    - assets/images/flags/country_ki_64.png
    - assets/images/flags/country_km_64.png
    - assets/images/flags/country_kn_64.png
    - assets/images/flags/country_kp_64.png
    - assets/images/flags/country_kr_64.png
    - assets/images/flags/country_kw_64.png
    - assets/images/flags/country_ky_64.png
    - assets/images/flags/country_kz_64.png
    - assets/images/flags/country_la_64.png
    - assets/images/flags/country_lb_64.png
    - assets/images/flags/country_lc_64.png
    - assets/images/flags/country_li_64.png
    - assets/images/flags/country_lk_64.png
    - assets/images/flags/country_lr_64.png
    - assets/images/flags/country_ls_64.png
    - assets/images/flags/country_lt_64.png
    - assets/images/flags/country_lu_64.png
    - assets/images/flags/country_lv_64.png
    - assets/images/flags/country_ly_64.png
    - assets/images/flags/country_ma_64.png
    - assets/images/flags/country_mc_64.png
    - assets/images/flags/country_md_64.png
    - assets/images/flags/country_me_64.png
    - assets/images/flags/country_mf_64.png
    - assets/images/flags/country_mg_64.png
    - assets/images/flags/country_mh_64.png
    - assets/images/flags/country_mk_64.png
    - assets/images/flags/country_ml_64.png
    - assets/images/flags/country_mm_64.png
    - assets/images/flags/country_mn_64.png
    - assets/images/flags/country_mo_64.png
    - assets/images/flags/country_mp_64.png
    - assets/images/flags/country_mq_64.png
    - assets/images/flags/country_mr_64.png
    - assets/images/flags/country_ms_64.png
    - assets/images/flags/country_mt_64.png
    - assets/images/flags/country_mu_64.png
    - assets/images/flags/country_mv_64.png
    - assets/images/flags/country_mw_64.png
    - assets/images/flags/country_mx_64.png
    - assets/images/flags/country_my_64.png
    - assets/images/flags/country_mz_64.png
    - assets/images/flags/country_na_64.png
    - assets/images/flags/country_nc_64.png
    - assets/images/flags/country_ne_64.png
    - assets/images/flags/country_nf_64.png
    - assets/images/flags/country_ng_64.png
    - assets/images/flags/country_ni_64.png
    - assets/images/flags/country_nl_64.png
    - assets/images/flags/country_no_64.png
    - assets/images/flags/country_np_64.png
    - assets/images/flags/country_nr_64.png
    - assets/images/flags/country_nu_64.png
    - assets/images/flags/country_nz_64.png
    - assets/images/flags/country_om_64.png
    - assets/images/flags/country_pa_64.png
    - assets/images/flags/country_pe_64.png
    - assets/images/flags/country_pf_64.png
    - assets/images/flags/country_pg_64.png
    - assets/images/flags/country_ph_64.png
    - assets/images/flags/country_pk_64.png
    - assets/images/flags/country_pl_64.png
    #- assets/images/flags/country_pm_64.png
    - assets/images/flags/country_pn_64.png
    - assets/images/flags/country_pr_64.png
    - assets/images/flags/country_ps_64.png
    - assets/images/flags/country_pt_64.png
    - assets/images/flags/country_py_64.png
    - assets/images/flags/country_qa_64.png
    #- assets/images/flags/country_re_64.png
    - assets/images/flags/country_ro_64.png
    - assets/images/flags/country_rs_64.png
    - assets/images/flags/country_ru_64.png
    - assets/images/flags/country_rw_64.png
    - assets/images/flags/country_sa_64.png
    - assets/images/flags/country_sb_64.png
    - assets/images/flags/country_sc_64.png
    - assets/images/flags/country_sd_64.png
    - assets/images/flags/country_se_64.png
    - assets/images/flags/country_sg_64.png
    - assets/images/flags/country_sh_64.png
    - assets/images/flags/country_si_64.png
    #- assets/images/flags/country_sj_64.png
    - assets/images/flags/country_sk_64.png
    - assets/images/flags/country_sl_64.png
    - assets/images/flags/country_sm_64.png
    - assets/images/flags/country_sn_64.png
    - assets/images/flags/country_so_64.png
    - assets/images/flags/country_sr_64.png
    - assets/images/flags/country_st_64.png
    - assets/images/flags/country_sv_64.png
    - assets/images/flags/country_sx_64.png
    - assets/images/flags/country_sy_64.png
    - assets/images/flags/country_sz_64.png
    - assets/images/flags/country_tc_64.png
    - assets/images/flags/country_td_64.png
    - assets/images/flags/country_tf_64.png
    - assets/images/flags/country_tg_64.png
    - assets/images/flags/country_th_64.png
    - assets/images/flags/country_tj_64.png
    - assets/images/flags/country_tk_64.png
    - assets/images/flags/country_tl_64.png
    - assets/images/flags/country_tm_64.png
    - assets/images/flags/country_tn_64.png
    - assets/images/flags/country_to_64.png
    - assets/images/flags/country_tr_64.png
    - assets/images/flags/country_tt_64.png
    - assets/images/flags/country_tv_64.png
    - assets/images/flags/country_tw_64.png
    - assets/images/flags/country_tz_64.png
    - assets/images/flags/country_ua_64.png
    - assets/images/flags/country_ug_64.png
    #- assets/images/flags/country_um_64.png
    - assets/images/flags/country_us_64.png
    - assets/images/flags/country_uy_64.png
    - assets/images/flags/country_uz_64.png
    - assets/images/flags/country_va_64.png
    - assets/images/flags/country_vc_64.png
    - assets/images/flags/country_ve_64.png
    - assets/images/flags/country_vi_64.png
    - assets/images/flags/country_vn_64.png
    - assets/images/flags/country_vu_64.png
    - assets/images/flags/country_wf_64.png
    - assets/images/flags/country_ws_64.png
    #- assets/images/flags/country_xk_64.png
    - assets/images/flags/country_ye_64.png
    - assets/images/flags/country_yt_64.png
    - assets/images/flags/country_za_64.png
    - assets/images/flags/country_zm_64.png
    - assets/images/flags/country_zw_64.png
